/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ImplementationRouteImport } from './routes/implementation'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplementationRoute = ImplementationRouteImport.update({
  id: '/implementation',
  path: '/implementation',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboard': typeof DashboardRoute
  '/documentation': typeof DocumentationRoute
  '/history': typeof HistoryRoute
  '/implementation': typeof ImplementationRoute
  '/knowledge': typeof KnowledgeRoute
  '/repositories': typeof RepositoriesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboard': typeof DashboardRoute
  '/documentation': typeof DocumentationRoute
  '/history': typeof HistoryRoute
  '/implementation': typeof ImplementationRoute
  '/knowledge': typeof KnowledgeRoute
  '/repositories': typeof RepositoriesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architecture': typeof ArchitectureRoute
  '/dashboard': typeof DashboardRoute
  '/documentation': typeof DocumentationRoute
  '/history': typeof HistoryRoute
  '/implementation': typeof ImplementationRoute
  '/knowledge': typeof KnowledgeRoute
  '/repositories': typeof RepositoriesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/architecture'
    | '/dashboard'
    | '/documentation'
    | '/history'
    | '/implementation'
    | '/knowledge'
    | '/repositories'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/architecture'
    | '/dashboard'
    | '/documentation'
    | '/history'
    | '/implementation'
    | '/knowledge'
    | '/repositories'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/architecture'
    | '/dashboard'
    | '/documentation'
    | '/history'
    | '/implementation'
    | '/knowledge'
    | '/repositories'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DashboardRoute: typeof DashboardRoute
  DocumentationRoute: typeof DocumentationRoute
  HistoryRoute: typeof HistoryRoute
  ImplementationRoute: typeof ImplementationRoute
  KnowledgeRoute: typeof KnowledgeRoute
  RepositoriesRoute: typeof RepositoriesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implementation': {
      id: '/implementation'
      path: '/implementation'
      fullPath: '/implementation'
      preLoaderRoute: typeof ImplementationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ArchitectureRoute: ArchitectureRoute,
  DashboardRoute: DashboardRoute,
  DocumentationRoute: DocumentationRoute,
  HistoryRoute: HistoryRoute,
  ImplementationRoute: ImplementationRoute,
  KnowledgeRoute: KnowledgeRoute,
  RepositoriesRoute: RepositoriesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
