import { createFileRoute } from "@tanstack/react-router";
import { PageHeader } from "@/components/app-shell";
import { Card } from "@/components/atlas-ui";
import { AiChat } from "@/components/ai-chat";
import { docs } from "@/lib/mock-data";
import { FileText, FolderTree, Edit3, RefreshCw, GitCompare, Download, ChevronRight, ChevronDown } from "lucide-react";
import { useState } from "react";

export const Route = createFileRoute("/documentation")({
  head: () => ({ meta: [{ title: "Documentation · CodeAtlas" }] }),
  component: DocumentationPage,
});

const tree = [
  { id: "core", label: "atlas-core", children: [
    { id: "d1", label: "Graph engine overview" },
    { id: "d5", label: "Incremental diffing" },
    { id: "d6", label: "Node model" },
  ]},
  { id: "agents", label: "atlas-agents", children: [
    { id: "d2", label: "Planner architecture" },
    { id: "d7", label: "Review agent" },
  ]},
  { id: "api", label: "atlas-api", children: [
    { id: "d3", label: "Request lifecycle" },
    { id: "d8", label: "Auth middleware" },
  ]},
  { id: "pay", label: "payments-svc", children: [
    { id: "d4", label: "Billing state machine" },
  ]},
];

function DocumentationPage() {
  const [active, setActive] = useState("d1");
  const [expanded, setExpanded] = useState<string[]>(["core", "agents"]);

  return (
    <div>
      <PageHeader
        eyebrow="Knowledge"
        title="Documentation"
        description="AI-generated, human-editable. Every doc stays in sync with the graph."
        actions={
          <>
            <button className="inline-flex items-center gap-2 rounded-lg border border-border bg-panel px-3 py-2 text-sm"><GitCompare className="h-4 w-4" /> Compare</button>
            <button className="inline-flex items-center gap-2 rounded-lg border border-border bg-panel px-3 py-2 text-sm"><Download className="h-4 w-4" /> Export</button>
            <button className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-sm font-medium text-primary-foreground"><RefreshCw className="h-4 w-4" /> Regenerate</button>
          </>
        }
      />

      <div className="grid min-h-[calc(100vh-140px)] grid-cols-1 lg:grid-cols-[260px_1fr_360px]">
        {/* Tree */}
        <aside className="hidden lg:block border-r border-border/70 bg-sidebar/40 p-3">
          <div className="mb-2 flex items-center gap-1.5 px-2 text-[11px] font-medium uppercase tracking-wider text-muted-foreground">
            <FolderTree className="h-3.5 w-3.5" /> Docs
          </div>
          {tree.map((folder) => {
            const open = expanded.includes(folder.id);
            return (
              <div key={folder.id} className="mb-1">
                <button
                  onClick={() => setExpanded((e) => e.includes(folder.id) ? e.filter((x) => x !== folder.id) : [...e, folder.id])}
                  className="flex w-full items-center gap-1.5 rounded-md px-2 py-1 text-sm hover:bg-panel/60"
                >
                  {open ? <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" /> : <ChevronRight className="h-3.5 w-3.5 text-muted-foreground" />}
                  <span className="font-medium">{folder.label}</span>
                </button>
                {open && (
                  <div className="ml-5 space-y-0.5">
                    {folder.children.map((c) => (
                      <button key={c.id} onClick={() => setActive(c.id)}
                        className={`flex w-full items-center gap-2 rounded-md px-2 py-1 text-left text-[13px] ${
                          active === c.id ? "bg-primary/15 text-foreground" : "text-muted-foreground hover:bg-panel/60"
                        }`}
                      >
                        <FileText className="h-3.5 w-3.5" />
                        <span className="truncate">{c.label}</span>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </aside>

        {/* Doc */}
        <div className="min-w-0 overflow-y-auto px-6 py-6 md:px-10">
          <div className="mx-auto max-w-3xl">
            <div className="mb-6 flex items-center justify-between">
              <div>
                <div className="text-[11px] font-mono text-muted-foreground">atlas-core / docs / graph-engine.md</div>
                <h2 className="mt-1 text-3xl font-semibold tracking-tight">Graph engine overview</h2>
                <div className="mt-2 flex items-center gap-2 text-[11px] text-muted-foreground">
                  <span>Updated 2h ago</span><span>·</span><span>Regenerated by Documentation Agent</span><span>·</span>
                  <span className="rounded-md border border-border bg-panel px-1.5 py-0.5 font-mono">v14</span>
                </div>
              </div>
              <div className="flex items-center gap-1.5">
                <button className="rounded-md border border-border bg-panel p-2 text-muted-foreground hover:text-foreground"><Edit3 className="h-3.5 w-3.5" /></button>
                <button className="rounded-md border border-border bg-panel p-2 text-muted-foreground hover:text-foreground"><RefreshCw className="h-3.5 w-3.5" /></button>
              </div>
            </div>

            <article className="prose prose-invert prose-sm max-w-none">
              <p className="lead text-base text-muted-foreground">
                The graph engine is the heart of CodeAtlas. It maintains a live, typed representation of every repository,
                service, module, API, and datastore, and streams incremental diffs to downstream agents.
              </p>

              <h3 className="mt-8 text-lg font-semibold">Architecture</h3>
              <p className="text-sm text-muted-foreground">
                Ingestion, resolution, and projection run as three cooperating passes over a persistent, content-addressed store.
                Each pass produces a versioned snapshot that downstream agents can subscribe to.
              </p>

              <pre className="mt-4 rounded-xl border border-border bg-panel/60 p-4 text-[12px] leading-relaxed overflow-x-auto">
{`type Node = {
  id: string
  kind: "repo" | "service" | "module" | "api" | "database" | "infra" | "ai"
  version: number
  hash: string
}

interface GraphEngine {
  scan(repo: Repository): Promise<Snapshot>
  diff(from: Snapshot, to: Snapshot): Diff
  subscribe(cb: (d: Diff) => void): Unsubscribe
}`}
              </pre>

              <h3 className="mt-8 text-lg font-semibold">Guarantees</h3>
              <ul className="mt-2 space-y-1.5 text-sm text-muted-foreground">
                <li>Snapshots are immutable and content-addressed.</li>
                <li>Diffs are minimal and reversible.</li>
                <li>Subscribers observe events at-least-once, with per-node ordering.</li>
              </ul>

              <blockquote className="mt-6 rounded-xl border-l-2 border-primary bg-panel/40 px-4 py-3 text-sm">
                <strong>Copilot suggestion:</strong> introduce a projection cache keyed on <code className="font-mono">(snapshot, agent)</code>
                to avoid re-computing agent-specific views. Estimated 34% reduction in P95 planning latency.
              </blockquote>

              <h3 className="mt-8 text-lg font-semibold">Related</h3>
              <div className="mt-2 grid grid-cols-1 gap-2 sm:grid-cols-2">
                {docs.map((d) => (
                  <div key={d.id} className="rounded-xl border border-border/60 bg-panel/40 p-3 text-sm">
                    <div className="font-medium">{d.title}</div>
                    <div className="text-[11px] text-muted-foreground">{d.repo} · {d.updated}</div>
                  </div>
                ))}
              </div>
            </article>
          </div>
        </div>

        {/* AI assistant */}
        <aside className="hidden lg:block border-l border-border/70 bg-sidebar/40">
          <AiChat compact />
        </aside>
      </div>

      <div className="hidden">
        <Card>_</Card>
      </div>
    </div>
  );
}
